apiVersion: v1
kind: Service
metadata:
  name: chunker-service
  labels:
    app: chunker-service
    app.kubernetes.io/name: chunker-service
    app.kubernetes.io/part-of: advanced-rag
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: chunker-service
