apiVersion: v1
kind: Namespace
metadata:
  name: models
  labels:
    opendatahub.io/dashboard: "true"
    modelmesh-enabled: "false"
  annotations:
    openshift.io/description: "Namespace for AI model deployments"
    openshift.io/display-name: "AI Models"
