# Granite Vision Service
---
apiVersion: v1
kind: Service
metadata:
  name: granite-vision
  labels:
    app: granite-vision
    component: vllm-inference
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: granite-vision
