apiVersion: v1
kind: Service
metadata:
  name: ms-marco-reranker-svc
  namespace: caikit-embeddings
  labels:
    app: ms-marco-reranker
spec:
  type: ClusterIP
  selector:
    serving.kserve.io/inferenceservice: ms-marco-reranker
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
