{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag-docling.fullname" . }}
  labels:
    {{- include "rag-docling.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "rag-docling.selectorLabels" . | nindent 4 }}
{{- end }}
