apiVersion: v1
kind: Service
metadata:
  name: embedding-service
  labels:
    app: embedding-service
    app.kubernetes.io/name: embedding-service
    app.kubernetes.io/part-of: advanced-rag
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    app: embedding-service
