apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: plan-service
  labels:
    app: plan-service
    app.kubernetes.io/name: plan-service
    app.kubernetes.io/part-of: advanced-rag
  annotations:
    haproxy.router.openshift.io/timeout: 120s
spec:
  to:
    kind: Service
    name: plan-service
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
