apiVersion: v1
kind: Service
metadata:
  name: vector-gateway
  labels:
    app: vector-gateway
    app.kubernetes.io/name: vector-gateway
    app.kubernetes.io/part-of: advanced-rag
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    app: vector-gateway
