{{- if and .Values.enabled .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rag-valkey.secretName" . }}
  labels:
    {{- include "rag-valkey.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ include "rag-valkey.password" . | b64enc | quote }}
{{- end }}
