{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag-valkey.fullname" . }}
  labels:
    {{- include "rag-valkey.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: valkey
      port: 6379
      targetPort: valkey
      protocol: TCP
  selector:
    {{- include "rag-valkey.selectorLabels" . | nindent 4 }}
{{- end }}
