apiVersion: v1
kind: Service
metadata:
  name: all-minilm-l6-v2-svc
  namespace: caikit-embeddings
  labels:
    app: all-minilm-l6-v2
spec:
  type: ClusterIP
  selector:
    serving.kserve.io/inferenceservice: all-minilm-l6-v2
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
